### ISSUE TITLE
BUG 如果给视图加了手势的话  就会屏蔽掉超链接的点击

### ISSUE THREAD

**Issue by darknessomi** [molon/MLEmojiLabel#10]
UITableViewCell上我加个View，然后给View加个点击的手势，再把MLEmojiLabel加在View上
然后点击超链接时直接是触发View手势的方法 并没有触发MLEmojiLabel的代理方法
再次测试的结果。。。  要长按才触发代理方法。。。

![8v z58 lrc l gggvw96](https://cloud.githubusercontent.com/assets/6939375/5772035/7936746e-9d85-11e4-858d-3c8eb4835d92.jpg)
点击后直接进入详细视图 并不触发代理方法
![b0nn679f f_n_sd8 q77rqx](https://cloud.githubusercontent.com/assets/6939375/5772039/84b7efca-9d85-11e4-9404-874f6f377248.jpg)
理论上应该是这样的
![a81 d n6wj3vi 23g g2u](https://cloud.githubusercontent.com/assets/6939375/5772040/8c824fb6-9d85-11e4-922f-8b4c768773ba.jpg)

**Comment by molon** [comment]
@darknessomi  已经在demo里添加了 这种情况的处理 范例。 [commit](https://github.com/molon/MLEmojiLabel/commit/2724064a17cbf9a1ff567824613a4819b25ca2a8)
