### ISSUE TITLE
对空格计算错误的bug

### ISSUE THREAD

**Issue by huapeng222** [molon/MLEmojiLabel#11]
![Uploading QQ20150121-2.png . . .]()
![Uploading QQ20150121-1.png . . .]()

hi,你好.
我的项目用到这个控件,刚刚发现如果内容前边全部是空格(比如聊天中,输入框中一直打空格,等到textView的结尾时,随便输入一个字符,)然后去生成气泡,这时候的size就会出现错误.刚刚用这里最新的代码也试了下也会出现这种问题
- (MLEmojiLabel *)emojiLabel1;这个方法下边这里这样改
  _emojiLabel1.text=@"(这里用很多的空格代替)a";
- (void)viewDidLoad里边这样改
  self.emojiLabel1.frame = CGRectMake(30, 64, size.width, size.height);(动态获取宽度)

**Comment by molon** [comment]
@huapeng222    
多谢提交这个BUG。   
我测试了一下，也查了一些资料，发现是CoreText方法`CTFramesetterSuggestFrameSizeWithConstraints`有BUG。   
测试代码   
```
NSAttributedString *attributedString = [[NSAttributedString alloc]initWithString:@"                                                                  a"];
    CTFramesetterRef framesetter = CTFramesetterCreateWithAttributedString((__bridge CFAttributedStringRef)attributedString);
    CGSize suggestedSize = CTFramesetterSuggestFrameSizeWithConstraints(framesetter, CFRangeMake(0, 0), NULL, CGSizeMake(224.0f, 10000), NULL);
    CFRelease(framesetter);

    NSLog(@"size:%@",NSStringFromCGSize(suggestedSize));
```

临时解决办法是
获取label的renderedAttributedText(此为label实际绘制的attributedString)，然后通过
```
        CGSize suggestedSize = [attributedString boundingRectWithSize:CGSizeMake(224.0f, MAXFLOAT)
                                                     options: NSStringDrawingUsesLineFragmentOrigin|NSStringDrawingUsesFontLeading context:nil].size;

```
iOS6+的计算文本高度方法设置label的size。   

很抱歉我暂时不能直接在代码里放入解决方案，我还需要去研究有没有更好的方法。

**Comment by cherishloveyou** [comment]
好像别的方法是用一个占位符来代替空格来计算

**Comment by sablib** [comment]
使用`boundingRectWithSize`方法计算size的话，文本中含有多个表情的时候计算出来的size仍然是不对的吧？

**Comment by ChinaJackSion** [comment]
自定义的表情发现计算出来的size不正确，有没有解决办法。只显示部分内容，其他的是省略号。

**Comment by molon** [comment]
@ChinaJackSion 可否提供下简单的测试代码。

**Comment by ChinaJackSion** [comment]
@molon 可以给个QQ之类的联系下吗？困扰了很久了，希望能帮下我😭

**Comment by molon** [comment]
@ChinaJackSion 这玩意不能私信啊。我加你吧。你的号多少。

**Comment by ChinaJackSion** [comment]
294566071

**Comment by jerroy** [comment]
只能用cocoa pods导入吗？demo里面依赖的东西好多

**Comment by molon** [comment]
@jerroy 就依赖了个TTT罢了啊

**Comment by JiXiangY** [comment]
我这里输入字符emoji 计算出来的尺寸也是不对的.比如下面这句话 展示出来的就少几个字
宽度限制185以内.
@所有人 くん後んっ顏😀😄😄😊😊😊😌😌😌🙂🙂🙂🙂😆😆😆🙃🙃😡😡😡😡😡😡群公告iOS9
![6800a47d-7584-4ea1-ad0c-983ec480b5d6](https://cloud.githubusercontent.com/assets/17586372/25373842/c1a6eb58-29cd-11e7-883b-7da1b7d45e46.png)

我查了好久 觉得也是这一句的问题
CGSize suggestedSize = CTFramesetterSuggestFrameSizeWithConstraints(framesetter, rangeToSize, NULL, constraints, NULL);
可是该如何修改呢?
如果改为      
CGSize suggestedSize = [label.attributedText boundingRectWithSize:CGSizeMake(224.0f, MAXFLOAT)
                                                     options: NSStringDrawingUsesLineFragmentOrigin|NSStringDrawingUsesFontLeading context:nil].size
这样 那图片表情就没法展示了/(ㄒoㄒ)/~~

**Comment by JiXiangY** [comment]
![Uploading 0B91D6B3-E365-45E4-B48B-7C15C7D98E43.png…]()
这里的 换行方式改成这样就可以了  是MLLabel 里面哪里换行方式和TTT的换行方式 有问题么 ?
ttt里的
NSAttributedStringAttributesFromLabel方法
        if (label.numberOfLines == 1) {
            paragraphStyle.lineBreakMode = label.lineBreakMode;
        } else {
//            paragraphStyle.lineBreakMode = NSLineBreakByWordWrapping;
             paragraphStyle.lineBreakMode = label.lineBreakMode;//改成
        }

**Comment by molon** [comment]
@JiXiangY 其实`label.attributedText`里已经预留了表情所占有的区域大小，所以只是用其来计算合适大小的话是OK的啊。

另外你图挂了，这个库不是MLLabel，推荐切换到MLLabel。
