### ISSUE TITLE
请问怎么给文字添加颜色

### ISSUE THREAD

**Issue by MonkeyS914** [molon/MLEmojiLabel#14]
MLEmojiLabel富文本很nice，但是现在碰到个问题，想支持设定文字颜色，由于是继承TTTAttributedLabel，不太熟悉，想请问下具体思路，因为文中都是用的nsstring作为参数

**Comment by molon** [comment]
@MonkeyS914  单独设置某区间文字颜色的话，请使用NSAttributedString
另外，如果项目支持iOS7+，可以尝试使用http://github.com/molon/MLLabel  :)
