### ISSUE TITLE
使用表情多的情况下会有卡顿现象出现

### ISSUE THREAD

**Issue by UINavigationController** [molon/MLEmojiLabel#15]
你好博主。我在项目中使用到了MLEmojiLabel，但是发现在一个滑动界面中使用到比较多的表情的时候会有卡顿现象出现。这种现象会造成非常不好的用户体验，有没有一种比较好的方法解决这种问题呢。比如做个缓存，预渲染什么的。期待你的回复

**Comment by molon** [comment]
使用https://github.com/molon/MLLabel 的话会好一些。但是极端情况下卡顿也会有那么一些，不过在可接受的范围之内。demo里测试的效果 和微信的感觉应该差不多。 你有兴趣可以测试下。
注意MLLabel只支持iOS7+
