### ISSUE TITLE
请问怎么实现粘贴板的功能

### ISSUE THREAD

**Issue by cl252738669** [molon/MLEmojiLabel#16]
你好  在demo里面看到
//这句测试剪切板
        [_emojiLabel1 performSelector:@selector(copy:) withObject:nil afterDelay:0.01f];

这句 这个copy的方法怎么触发呢？

**Comment by cl252738669** [comment]
创建开始就调用了   但是怎么才知道 复制成功了呢，？  我comment + v  没有显示复制的东西啊？？

**Comment by molon** [comment]
@cl252738669 为什么要command+v   你在手机里能输入文本的地方长按粘贴啊。
