### ISSUE TITLE
发现空格或者换行过多会卡死UI 

### ISSUE THREAD

**Issue by ljssafe** [molon/MLEmojiLabel#18]
不知道是什么情况，没查出来  换行过多或者空格过多就会卡死UI 动不了了

**Comment by molon** [comment]
@ljssafe 可以麻烦给个代码例子么? 我需要查下。 :)

**Comment by ljssafe** [comment]
demo 好了 如何发给你？

在 2015-08-25 22:32:21，"molon" <notifications@github.com> 写道：


@ljssafe 可以麻烦给个代码例子么? 我需要查下。 :)

**Comment by ljssafe** [comment]
可以把空格去掉10个就可以进入tableview了 否则就卡在启动界面




在 2015-08-25 22:32:21，"molon" <notifications@github.com> 写道：


@ljssafe 可以麻烦给个代码例子么? 我需要查下。 :)

**Comment by molon** [comment]
@ljssafe dudl@qq.com

**Comment by molon** [comment]
@ljssafe 哥们，抱歉才发现你的邮件。
我看了下，你这个不知道是啥时候的代码了，还是修改版的。
我把最新的label丢进去是不会发生你这种情况的。:) 你可以尝试下。

**Comment by ljssafe** [comment]
@molon o 哦 ，最新版的我发现那个点击时候背景颜色的位置计算貌似没有之前那个版本的精确，新版点击背景色的位置偏移有些厉害

**Comment by ljssafe** [comment]
@molon o 哦 ，最新版的我发现那个点击时候背景颜色的位置计算貌似没有之前那个版本的精确，新版点击背景色的位置偏移有些厉害

**Comment by ljssafe** [comment]
@molon o 哦 ，最新版的我发现那个点击时候背景颜色的位置计算貌似没有之前那个版本的精确，新版点击背景色的位置偏移有些厉害

**Comment by ljssafe** [comment]
@molon o 哦 ，最新版的我发现那个点击时候背景颜色的位置计算貌似没有之前那个版本的精确，新版点击背景色的位置偏移有些厉害

**Comment by ljssafe** [comment]
@molon o 哦 ，最新版的我发现那个点击时候背景颜色的位置计算貌似没有之前那个版本的精确，新版点击背景色的位置偏移有些厉害

**Comment by molon** [comment]
@ljssafe 这个没有发现啊。怎么才能重现你说的问题。
