### ISSUE TITLE
替换了最新的TTTAttributedLabel

### ISSUE THREAD

**Issue by ZWZZZ** [molon/MLEmojiLabel#21]
替换了最新的TTTAttributedLabel之后，自定义表情显示不了

**Comment by molon** [comment]
@ZWZZZ 抱歉，放假在家没有电脑。只能等节后再帮助解决了。

**Comment by ZWZZZ** [comment]
@molon 哈哈，我也是国庆无聊在家才发现这个问题的

**Comment by CheaterHu** [comment]
为什么设置行高无效啊

**Comment by CheaterHu** [comment]
行间距，我做出来行间距不均匀而且没法看

**Comment by showshaw** [comment]
自定义表情显示不了的问题有解决方案吗

**Comment by molon** [comment]
@showshaw @ZWZZZ  我刚修改了代码使得不改动TTT内部代码为前提实现功能。
同时支持了pod，这样以后TTT有更新也不怕了。

@CheaterHu 我这边测试设置行高没有问题，请问你是如何设置的呢，呃，如果也是因为最新TTT的话。新修改MLEmojiLabel代码测试还是有问题，请新开个issue，毕竟是不同问题。:)

**Comment by CheaterHu** [comment]
@molon 解决了，是因为我设置方式不对，(其实感觉这里面有点误导人啊，传一个属性字串（大小颜色都设定好）然后再用TTT的属性就不能用了，正如ML中所说的注意的问题一样。个人感觉通过属性来设置不应该失效)。  谢谢大神回复！

**Comment by molon** [comment]
@CheaterHu 个人感觉的确这样不是太好。但是这个问题是TTT本身的设计问题。 如果有兴趣可以尝试 http://github.com/molon/MLLabel ，对这个问题有做很好的处理。 :)
