### ISSUE TITLE
邮箱、链接、电话检测无法单独禁用 ?

### ISSUE THREAD

**Issue by showshaw** [molon/MLEmojiLabel#24]
设置_contentLabel.enabledTextCheckingTypes = NSTextCheckingTypeLink;后邮箱、链接、电话类型都检测了.设置_emojiLabel.disableThreeCommon = YES没有效果 . 可以单独禁用某一项吗 , 需求是仅仅检测URL和表情,其他保持原样

**Comment by molon** [comment]
@showshaw 抱歉，暂时不支持如此。或许可以试试我另外一个库。http://github.com/molon/MLLabel
