### ISSUE TITLE
你好 ，关于类似微信UIMenuController功能

### ISSUE THREAD

**Issue by yiyangBOB** [molon/MLEmojiLabel#25]
请问怎么加上，我加失败了。在我自己的view上面
- (void)attributedLabel:(TTTAttributedLabel *)label didLongPressLinkWithTextCheckingResult:(NSTextCheckingResult *)result atPoint:(CGPoint)point
{
    [self becomeFirstResponder];
    UIMenuItem *copyLink = [[UIMenuItem alloc] initWithTitle:@"复制"
                                                      action:@selector(copy:)];
    [[UIMenuController sharedMenuController] setMenuItems:[NSArray arrayWithObjects:copyLink, nil]];
    [[UIMenuController sharedMenuController] setTargetRect:CGRectMake(0, 0, 100, 30) inView:self.superview];
    [[UIMenuController sharedMenuController] setMenuVisible:YES animated: YES];
}

**Comment by molon** [comment]
@yiyangBOB 哥们，这个问题和这个库没有什么关联啊。 
如果需要实现menu的话，至少view需要至少得实现`canBecomeFirstResponder`和`canPerformAction:withSender`功能。而你这里`becomeFirstResponder`的view不知是否实现了。
