### ISSUE TITLE
你好，咨询个问题。

### ISSUE THREAD

**Issue by zuoerjin** [molon/MLEmojiLabel#31]
关于电话号码的链接的展示。
服务返回类似[tel=000000]111。要只显示000000111。并且还能出现点击000000拨打电话的链接。
我看代码，现在是先label赋值，最后处理的添加链接。
现在[tel=] 这部分一直去不掉。  去掉了最后添加链接就会有问题。 
请问，能不能帮忙指点一下。谢谢

**Comment by molon** [comment]
这种需求的话此库实际上是不支持的。
发觉你这种需求还蛮多的，我就刚刚给库加了个方法，但是是在`MLLabel`里的，你可以去试试看，但是现在还没release，你需要手动clone下来尝试。
在demo里的Link页面里的8和9号。
https://github.com/molon/MLLabel

**Comment by celebrateWhy** [comment]
你好，我想知道我点击的是哪个标签，类似tag这样的，这个可以获取到吗，十分感谢

**Comment by molon** [comment]
@celebrateWhy 不是很明白你的意思。。 如果只是想获取tag的话，你能获取到点击的Label，直接.tag就可以了啊

**Comment by celebrateWhy** [comment]
十分感谢回答，我的问题是，我在一个lable里面有 好多个可以点击的地方 比如 aaa//@张三:aaa//@李四:bbb//@李五:ccc  这样子 我点击张三 李四 李五 是可以获取到我点击的名字的  可是我想知道我点击的是第几个  比如张三是第一个 李四是第二个 李五是第三个  我想知道点击的是哪个  这样可以吗？

**Comment by molon** [comment]
@celebrateWhy 这个的话挺抱歉，并不支持这个功能。 如果一定要实现的话，需要你自己去多做些工作了。
首先一般MLEmojiLabel我不会再加新东西了，现在主要维护`MLLabel`。
其中`MLLinkLabel`的话，有个links属性，代表当前Label所识别到的所有Link，但是它不一定是排序后的，如果你一定想要知道序号，可以在点击回调里手动将links以linkRange顺序排序，再去获取点击的Link在排序后的links里的位置即可。

**Comment by celebrateWhy** [comment]
嗯嗯，好的，非常感谢提供思路，谢谢你。
