### ISSUE TITLE
怎么我用了这个控件，我的链接点了没有反应呢？？？delegate完全不触发！？

### ISSUE THREAD

**Issue by Heinoc** [molon/MLEmojiLabel#33]
怎么我用了这个控件，我的链接点了没有反应呢？？？delegate完全不触发！？

**Comment by Heinoc** [comment]
在uitableviewvell中，点击链接，delegate不触发

**Comment by molon** [comment]
你是不是cell上添加了手势啊啥的，如果是的话看demo里的TableViewCell，里面的手势delegate处理

**Comment by Heinoc** [comment]
昨天晚上写晕了，套在了cell里的uiview里，uiview没有打开userInteractionEnabled。。。。现在可以了，但是现在我的链接只能显示“http://”。。。怎么解 = =

![image](https://cloud.githubusercontent.com/assets/5534122/17687852/6d102c8c-63ab-11e6-972d-88deed03b070.png)

**Comment by molon** [comment]
@Heinoc 。。。  没遇见过这情况，能在demo里重现么？可以的话请fork项目重现，我来调下。

**Comment by Heinoc** [comment]
@molon 呃。。。被我找到原因了。。应该是给text加样式的时候，set的attribute比正常的text的长度要长。。我给label加长了2个像素就好了。。。

不过发现了另一个问题，ip地址的url不能识别成网址呀（ps：我问题怎么这么多 = =）

![51c4b327-a7d6-4b68-a0b3-ce180696a30d](https://cloud.githubusercontent.com/assets/5534122/17688868/b3b5d1be-63b5-11e6-942c-5974d66d7615.png)

**Comment by molon** [comment]
https://github.com/molon/MLEmojiLabel/commit/ef2227cdaebca2da931da4e2fffbf3a21bf1c3cc
