### ISSUE TITLE
能支持富文本吗？

### ISSUE THREAD

**Issue by qcdnjeff** [molon/MLEmojiLabel#38]
使用时发现attributedText赋值NSAttributedString并没有什么反应

**Comment by molon** [comment]
可以啊，demo里有设置富文本的例子你仔细瞅下。

**Comment by qcdnjeff** [comment]
哦，我问的不太对，对html的可支持么？

NSString * htmlString = @" <html><body>Some html string \n<font size=\"13\" color=\"red\">This is some text!</font></body>";

**Comment by molon** [comment]
@qcdnjeff html转attr的方法库里没。
https://github.com/molon/MLLabel/blob/master/Classes/Category/NSAttributedString%2BMLLabel.m
这里有，你可以参考自己整下。但是这东西(官方提供的)我感觉不咋靠谱啊，性能极差，如果一定要有这种需求的话建议尝试下DTCoreText
