### ISSUE TITLE
在global线程中，创建MLEmojiLable时，挂掉

### ISSUE THREAD

**Issue by MeakerSy** [molon/MLEmojiLabel#39]
在tableView的cell中会用到MLEmojiLable，当服务器中数据回来时，在异步线程中会创建MLEmojiLable，计算大小等存储在一个数组中，全部创建好了后，再在主线程中直接在主线程中使用刚创建出来的MLEmojiLable，以减少大量表情带来的卡顿。
但经常会出现，在异步线程中创建MLEmojiLable时，挂掉的情况。
挂掉的log有下面三种：
 libsystem_platform.dylib _sigtramp + 52
 CoreFoundation -[__NSSetM addObject:]
 UIKit _UIViewDidSetNeedsDisplay
 UIKit -[UILabel setUserInteractionEnabled:]
 UIKit -[UILabel _commonInit]
 UIKit -[UILabel initWithFrame:]
 -[TTTAttributedLabel initWithFrame:] TTTAttributedLabel.m:333

第二种：
libsystem_platform.dylib _sigtramp + 52
CoreFoundation -[__NSSetM addObject:]
UIKit _UIViewDidSetNeedsDisplay
UIKit -[UILabel setUserInteractionEnabled:]
[MLEmojiLabel commonInit] MLEmojiLabel.m:136
 [TTTAttributedLabel initWithFrame:] TTTAttributedLabel.m:340

第三种
 libsystem_platform.dylib _sigtramp + 52
 CoreFoundation -[__NSSetM addObject:]
 UIKit _UIViewDidSetNeedsDisplay
-[TTTAttributedLabel setAttributedText:] TTTAttributedLabel.m:434
-[TTTAttributedLabel setText:] TTTAttributedLabel.m:1067
 -[MLEmojiLabel setEmojiText:] MLEmojiLabel.m:515
-[MLEmojiLabel setLineBreakMode:] MLEmojiLabel.m:681
-[MLEmojiLabel commonInit] MLEmojiLabel.m:155
 -[TTTAttributedLabel initWithFrame:] TTTAttributedLabel.m:340

TTTAttributedLabel.m:333中的内容是：
- (instancetype)initWithFrame:(CGRect)frame {
    self = [super initWithFrame:frame];
    if (!self) {
        return nil;
    }

    [self commonInit];

    return self;
}

**Comment by molon** [comment]
抱歉，不支持异步线程。。对流畅性有强要求可以尝试YYText
