### ISSUE TITLE
Xcode5报错20多个，Xcode6正常

### ISSUE THREAD

**Issue by darknessomi** [molon/MLEmojiLabel#9]
试问如何才能支持Xcode5？
还有就是看上去表情显示貌似是基于微信的  微博的plist不行  我看到dome里 解析出来的是字典  而微博的是数组 数组的元素是字典，如何解决？

**Comment by molon** [comment]
只能手动整理成我demo里这样的。 sign字符->图像名 这样的字典形式。 写份代码去整理应该也不麻烦吧，或者你自己在源码里修改呗。  (其实微博这样做蛮好的，因为实际项目里sign字符列表会有排序的需求，而我demo里是单开了一份plist作为排序用。由于也有部分人在用此库，会改变用法的不太方便修改。)   

另外XCode5报错，我猜测应该主要是我更新了TTTAttributeLabel的原因，由于我已经把XCode5扔了，这边已然测试不了，也并不打算处理了，见谅。:)
